---
title: "Analysis for Project"
output: 
  html_document: 
    fig_height: 6
    fig_width: 9
    toc: yes
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("useful_functions.R")
```

# Introduction
<a href="#top">Back to top</a>

Use this R Markdown to perform the main analysis for the project. I use this basically as a lab notebook. It contains the main analysis and a variety of sensitivity analysis. The code in this documents serves as a baseline for the eventual tables and figures that will go into the paper. At the same time it will serve as a record of all supplementary analyses performed. 



porn$days_avail <- as.numeric(as.Date("2013-02-28")-porn$upload_date)
porn$popularity <- porn$nb_views/porn$days_avail
porn$upload_year <- as.numeric(format(porn$upload_date, "%Y"))



#Creating master list of tags for analysis
tags.super <- c("ethnicity",
                "race",
#               "hair",
                "sex.act",
                "fetish",
#               "bdsm.super",
#               "age",
                "voyeur.super",
#               "trans",
                "gay",
                "breasts" 
#                "Amateur", 
#                "Teens", 
#                "Hardcore"
                )



trends <- NULL
for(tag in tags.super) {
  cat(tag)
  cat("\n")
  temp <- data.frame(year=2007:2013,
                     tag=tag,
                     percent=100*prop.table(table(porn$upload_year, porn[,tag]),1)[,2])
  
  trends <- rbind(trends, temp)
  
}

#Plotting group % by year
ggplot(trends, aes(x=year, y=percent, color=tag, group=tag))+
  geom_point()+
  geom_smooth(se=FALSE)+
  theme_bw()+
  labs(x="Year",
        y="Percent of total videos uploaded",
        title="Major Themes in Pornography Published to XHamster: 2007-2013",
       colour="Theme")

#










#Deprecated Script




#Create subsample
porn.subsample <- porn[sample(1:nrow(porn), 5000),]



ggplot(porn, aes(x=upload_date, y=popularity, color=tag, group=tag))+
  geom_point(alpha=0.1)+
  geom_smooth(method="gam")+
  scale_y_log10()

ggplot(porn, aes(x=days_avail, y=nb_views))+
  geom_point(alpha=0.1)+
  geom_smooth(method="gam")+
  theme_bw()

#swap porn for porn.subsample and vice versa; porn will take much longer
temp <- poLCA(as.formula(paste("cbind(",paste(tags.super,collapse=","),")~1",sep="")), 
              porn.subsample, nclass=3)
